### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by csnelsonchu** [xkortex/Siraj_Chatbot_Challenge#1]
Hi Mike,

Thank you for sharing your work.
I am getting a syntax error when running this on python 3.
File: https://github.com/xkortex/Siraj_Chatbot_Challenge/blob/master/preprocess.py
Line 251: self._lookup = { **word_idx } # deal with null cases if necessary

Any idea what I am missing?

Thanks
Nelson

**Comment by JacobChrist** [comment]
Are you running the preprocess.py or main.py?  It works for me at the head as of this writing (a2664666da83273eac2c4923a3ea903c887ed59c)

**Comment by csnelsonchu** [comment]
Hi Jacob,
I am running main.py using the following command
python3 main.py

**Comment by xkortex** [comment]
@csnelsonchu [Dictionary unpacking is a feature as of 3.5](http://stackoverflow.com/a/26853961/3988037). If you want to use that syntax, you can upgrade your python. 

However I just replaced it with this line since I don't need to merge dicts anymore. 
```python
self._lookup = dict(word_idx)
```

Just patched it with 5557135098530a6ce6d9210561b3dbe1b2b18f9c so give that a pull. The unpack syntax was leftover cruft from when I was merging dicts, so I just made it an object copy.

**Comment by csnelsonchu** [comment]
Works Great.
Thanks Mike!
